import { EdgeTTS } from "edge-tts-universal";
import * as fs from "node:fs";
import * as path from "node:path";
import { normalizePronunciation } from "./normalizer";

export interface SceneAudioInput {
  id: string;
  text: string;
  spokenText?: string;
  voice?: string;
}

export interface SceneAudioOutput {
  id: string;
  text: string;
  spokenText: string;
  audioPath: string;
  filePath: string;
  sizeBytes: number;
  estimatedDurationSec: number;
  durationInFrames: number;
}

export interface AudioManifest {
  topic: string;
  engine: string;
  voice: string;
  totalScenes: number;
  totalDurationFrames: number;
  totalDurationSec: number;
  scenes: SceneAudioOutput[];
  generatedAt: string;
}

/**
 * Synthesizes audio using EdgeTTS (free, online, no GPU required).
 */
export async function synthesizeEdgeTTSBatch(
  topicKey: string,
  scenes: SceneAudioInput[],
  options: {
    voice?: string;
    outputDir?: string;
    fps?: number;
    bufferFrames?: number;
    targetSrcDir?: string;
  } = {}
): Promise<AudioManifest> {
  const voice = options.voice || "vi-VN-NamMinhNeural";
  const outputDir = options.outputDir || path.resolve(process.cwd(), "public/audio");
  const fps = options.fps || 30;
  const bufferFrames = options.bufferFrames ?? 3;

  const topicDir = path.join(outputDir, topicKey);
  fs.mkdirSync(topicDir, { recursive: true });

  const results: SceneAudioOutput[] = [];
  let totalFrames = 0;

  console.log(`\n🎙️ [EdgeTTS] Synthesizing topic: '${topicKey}' (${scenes.length} scenes, voice: ${voice})...`);

  for (let i = 0; i < scenes.length; i++) {
    const scene = scenes[i];
    const sceneId = scene.id || `scene_${i + 1}`;
    const text = scene.text;
    const rawSpoken = scene.spokenText || text;
    // Apply pronunciation normalizer for technical terms
    const normalizedSpoken = normalizePronunciation(rawSpoken);

    const destFile = path.join(topicDir, `${sceneId}.mp3`);
    console.log(`[${i + 1}/${scenes.length}] Synthesizing '${sceneId}'...`);

    // Dynamic import to support ESM/CJS universal module
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const edgeTtsModule: any = await import("edge-tts-universal");
    const CommunicateClass =
      edgeTtsModule.Communicate ||
      edgeTtsModule.default?.Communicate ||
      edgeTtsModule.UniversalCommunicate ||
      edgeTtsModule.IsomorphicCommunicate ||
      edgeTtsModule.default;

    const communicate = new CommunicateClass(normalizedSpoken, {
      voice: scene.voice || voice,
      rate: "+5%",
      pitch: "+0Hz",
      volume: "+0%",
    });

    const chunks: Buffer[] = [];
    for await (const chunk of communicate.stream()) {
      if (chunk.type === "audio" && chunk.data) {
        if (Buffer.isBuffer(chunk.data)) {
          chunks.push(chunk.data);
        } else if (chunk.data instanceof Uint8Array || chunk.data instanceof ArrayBuffer) {
          chunks.push(Buffer.from(chunk.data));
        }
      }
    }

    const audioBuffer = Buffer.concat(chunks);
    if (audioBuffer.length === 0) {
      throw new Error(`EdgeTTS returned 0 bytes for ${sceneId}`);
    }

    fs.writeFileSync(destFile, audioBuffer);

    const stats = fs.statSync(destFile);
    // 96kbitrate mono MP3 ~ 12,000 bytes/sec
    const estSec = Math.max(1, Math.round((stats.size / 12000) * 10) / 10);
    const frames = Math.ceil(estSec * fps) + bufferFrames;

    const res: SceneAudioOutput = {
      id: sceneId,
      text,
      spokenText: normalizedSpoken,
      audioPath: `audio/${topicKey}/${sceneId}.mp3`,
      filePath: destFile,
      sizeBytes: stats.size,
      estimatedDurationSec: estSec,
      durationInFrames: frames,
    };

    results.push(res);
    totalFrames += frames;
    console.log(`   ✓ Done: ${estSec}s (~${frames} frames)`);
  }

  const totalSec = Math.round((totalFrames / fps) * 10) / 10;
  const manifest: AudioManifest = {
    topic: topicKey,
    engine: "EdgeTTS",
    voice,
    totalScenes: scenes.length,
    totalDurationFrames: totalFrames,
    totalDurationSec: totalSec,
    scenes: results,
    generatedAt: new Date().toISOString(),
  };

  // Save manifest.json
  const manifestPath = path.join(topicDir, "manifest.json");
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), "utf-8");

  // Save audioData.ts in target source dir if provided or exists
  const targetDir = options.targetSrcDir || path.resolve(process.cwd(), `src/${topicKey}`);
  if (fs.existsSync(targetDir)) {
    const tsCode = `// Auto-generated by Auto_create_video TTS Engine
export const audioManifest = ${JSON.stringify(manifest, null, 2)} as const;
`;
    fs.writeFileSync(path.join(targetDir, "audioData.ts"), tsCode, "utf-8");
    console.log(`📄 Generated TypeScript manifest: ${path.join(targetDir, "audioData.ts")}`);
  }

  console.log(`\n🎉 Generated all ${scenes.length} EdgeTTS audio files (${totalSec}s)`);
  return manifest;
}
