import * as fs from "node:fs";
import * as path from "node:path";
import { AudioManifest } from "../tts/edge_tts_runner";

/**
 * Calculates total frames for a series of scenes and outputs TypeScript definitions.
 */
export function calculateVideoTotalFrames(
  manifest: AudioManifest,
  bufferPerScene = 3,
  outroExtra = 10
): number {
  let total = 0;
  manifest.scenes.forEach((scene, index) => {
    const isOutro = index === manifest.scenes.length - 1;
    total += scene.durationInFrames + (isOutro ? outroExtra : bufferPerScene);
  });
  return total;
}

/**
 * Updates or creates audioData.ts in target directory.
 */
export function saveAudioManifestFile(targetDir: string, manifest: AudioManifest) {
  fs.mkdirSync(targetDir, { recursive: true });
  const content = `// Auto-generated by Auto_create_video manifest generator
export const audioManifest = ${JSON.stringify(manifest, null, 2)} as const;
`;
  fs.writeFileSync(path.join(targetDir, "audioData.ts"), content, "utf-8");
}
