export const audioManifest = {
  topic: "AIBirthExplainer",
  totalScenes: 8,
  scenes: [
    {
      id: "scene1_hook",
      text: "Nhiều người nghĩ rằng Trí tuệ nhân tạo (AI) là một thứ phép thuật siêu nhiên vừa được phát minh vài năm gần đây. Nhưng sự thật sẽ khiến bạn ngã ngửa: 90% nền tảng toán học của AI đã được các nhà khoa học nghĩ ra từ thời ông bà chúng ta! Vậy tại sao suốt hơn nửa thế kỷ, AI từng bị cả thế giới ruồng bỏ, bị xem là một dự án ma lừa đảo tiền của chính phủ? Sự thật đỉnh chóp đằng sau là gì?",
      audioPath: "audio/AIBirthExplainer/scene1_hook.mp3",
      filePath: "F:\\Video\\Video\\public\\audio\\AIBirthExplainer\\scene1_hook.mp3",
      estimatedDurationSec: 23.48,
      durationInFrames: 705,
    },
    {
      id: "scene2_alan_turing",
      text: "Mọi chuyện bắt đầu vào năm 1950, khi thiên tài toán học Alan Turing đặt ra câu hỏi huyền thoại: 'Liệu cỗ máy có biết suy nghĩ?'. Đến năm 1956, tại hội nghị Dartmouth, thuật ngữ 'Trí tuệ nhân tạo' chính thức ra đời. Thời điểm đó, sự lạc quan lên đến đỉnh điểm. Các giáo sư hàng đầu tự tin tuyên bố: Chỉ trong vòng 20 năm nữa, máy tính sẽ làm được mọi việc mà bộ não con người làm được!",
      audioPath: "audio/AIBirthExplainer/scene2_alan_turing.mp3",
      filePath: "F:\\Video\\Video\\public\\audio\\AIBirthExplainer\\scene2_alan_turing.mp3",
      estimatedDurationSec: 24.68,
      durationInFrames: 741,
    },
    {
      id: "scene3_first_winter",
      text: "Thế nhưng, đời không như là mơ! Năm 1958, cỗ máy Perceptron - mô hình nơ-ron nhân tạo đầu tiên ra đời. Người ta tung hô nó như một vị thần. Nhưng chỉ vài năm sau, một thảm họa logic xảy ra: Perceptron gục ngã hoàn toàn trước một phép tính sơ đẳng nhất - Phép toán XOR! Năm 1969, cuốn sách của Marvin Minsky chỉ ra rằng mạng nơ-ron là một ngõ cụt vô vọng. Cú sốc này khiến các nhà tài trợ rút vốn hàng loạt, phòng thí nghiệm đóng cửa. Kỷ nguyên tăm tối đầu tiên mang tên 'Mùa đông AI' chính thức ập đến suốt gần 15 năm!",
      audioPath: "audio/AIBirthExplainer/scene3_first_winter.mp3",
      filePath: "F:\\Video\\Video\\public\\audio\\AIBirthExplainer\\scene3_first_winter.mp3",
      estimatedDurationSec: 36.01,
      durationInFrames: 1081,
    },
    {
      id: "scene4_backpropagation",
      text: "Giữa lúc cả thế giới quay lưng, vẫn có những nhà khoa học bị coi là 'gàn dở' âm thầm nghiên cứu trong bóng tối, tiêu biểu là Geoffrey Hinton. Họ phát hiện ra rằng: Một nơ-ron không giải được XOR, nhưng nếu xếp nhiều tầng nơ-ron lại với nhau, chúng sẽ có sức mạnh vô hạn! Thuật toán Lan truyền ngược (Backpropagation) ra đời, giúp mạng nơ-ron tự học và tự sửa sai. Nhưng cay đắng thay: Thuật toán cực kỳ thông minh, nhưng máy tính thời bấy giờ lại quá rùa bò! Để huấn luyện một mô hình nhỏ xíu, máy tính phải chạy ròng rã cả tháng trời. AI lại rơi vào Mùa đông lần thứ hai!",
      audioPath: "audio/AIBirthExplainer/scene4_backpropagation.mp3",
      filePath: "F:\\Video\\Video\\public\\audio\\AIBirthExplainer\\scene4_backpropagation.mp3",
      estimatedDurationSec: 34.47,
      durationInFrames: 1035,
    },
    {
      id: "scene5_alexnet_gpu",
      text: "Và rồi, bước ngoặt vĩ đại nhất lịch sử công nghệ đã xuất hiện vào năm 2012 tại cuộc thi nhận diện hình ảnh ImageNet. Nhóm nghiên cứu của Geoffrey Hinton đã làm một điều chưa ai từng nghĩ tới: Thay vì dùng chip CPU truyền thống, họ lấy 2 chiếc cạc đồ họa chơi game bình thường của NVIDIA - chiếc GeForce GTX 580 - để huấn luyện mạng nơ-ron mang tên AlexNet! Kết quả khiến toàn bộ giới khoa học rúng động: AlexNet đè bẹp tất cả các đối thủ với khoảng cách không tưởng! Hóa ra, mạng nơ-ron không hề sai, mà nó chỉ phải ngủ đông suốt 40 năm... để chờ chip bán dẫn xử lý song song ra đời!",
      audioPath: "audio/AIBirthExplainer/scene5_alexnet_gpu.mp3",
      filePath: "F:\\Video\\Video\\public\\audio\\AIBirthExplainer\\scene5_alexnet_gpu.mp3",
      estimatedDurationSec: 34.21,
      durationInFrames: 1027,
    },
    {
      id: "scene6_transformer_llm",
      text: "Từ cú nổ năm 2012, AI phát triển với tốc độ tên lửa. Đến năm 2017, Google tung ra bài báo khoa học kinh điển 'Attention Is All You Need', khai sinh kiến trúc Transformer. Nó giúp máy tính hiểu được ngữ cảnh ngôn ngữ toàn cục, mở đường cho sự bùng nổ của ChatGPT, Claude hay Gemini ngày nay. Nhưng đi cùng sức mạnh đó là một cái giá đắt đỏ: Những mô hình này ngốn hàng chục ngàn cạc đồ họa cao cấp và tiêu thụ lượng điện năng tương đương cả một thành phố!",
      audioPath: "audio/AIBirthExplainer/scene6_transformer_llm.mp3",
      filePath: "F:\\Video\\Video\\public\\audio\\AIBirthExplainer\\scene6_transformer_llm.mp3",
      estimatedDurationSec: 28.13,
      durationInFrames: 844,
    },
    {
      id: "scene7_edge_ai_revolution",
      text: "Và đây mới là đỉnh chóp thực sự của tương lai: Chúng ta không thể mang cả một phòng máy chủ đặt lên xe ô tô tự hành, drone bay trên trời hay thiết bị y tế đeo trên tay. Xu hướng tất yếu đang diễn ra: Đưa AI rời khỏi đám mây để chạy trực tiếp trên chip phần cứng - gọi là Edge AI và TinyML! Các mô hình AI được nén hàng trăm lần, chạy mượt mà trên vi điều khiển nhỏ bằng móng tay như STM32 hay ESP32 với mức tiêu thụ điện chỉ vài miliwatt!",
      audioPath: "audio/AIBirthExplainer/scene7_edge_ai_revolution.mp3",
      filePath: "F:\\Video\\Video\\public\\audio\\AIBirthExplainer\\scene7_edge_ai_revolution.mp3",
      estimatedDurationSec: 25.59,
      durationInFrames: 768,
    },
    {
      id: "scene8_outro",
      text: "Nhìn lại hành trình 70 năm, bạn sẽ thấy: AI không phải là sự xuất hiện ngẫu nhiên, mà là cuộc hôn nhân vĩ đại giữa Thuật toán toán học và Sức mạnh phần cứng chip bán dẫn. Nếu bạn muốn trở thành người làm chủ làn sóng công nghệ tiếp theo thay vì chỉ là người dùng, hãy bắt đầu từ nền tảng vững chắc nhất: Lập trình C, Kiến trúc máy tính và Hệ thống nhúng. Truy cập ngay embedded-aiot.com và theo dõi kênh Ngoc Einstein để cùng chinh phục thế giới phần cứng và AI!",
      audioPath: "audio/AIBirthExplainer/scene8_outro.mp3",
      filePath: "F:\\Video\\Video\\public\\audio\\AIBirthExplainer\\scene8_outro.mp3",
      estimatedDurationSec: 25.63,
      durationInFrames: 769,
    }
  ],
  generatedAt: "2026-09-22T10:28:14.686Z",
} as const;
